# Pandas Basic

## 파일 입출력
- 데이터프레임을 csv 파일로 저장하기
- 저장된 csv 파일을 불러오기

In [8]:
#항상 현재 경로를 확인하고 시작한다
import os
os.getcwd()

'/Users/angela/multicampus28/python/machine_learning'

In [6]:
import pandas as pd

sample_df = pd.DataFrame({"col1" : [1, 2], "col2" : [3, 4]})
sample_df 

#파일명:test.csv, index=False 로 저장하기(내보내기)
sample_df.to_csv('./output/test.csv', index=False)

In [9]:
# 파일불러오기(output 폴더 안에 test.csv)

df = pd.read_csv("./output/test.csv")
df

col1  col2
0     1     3
1     2     4

In [11]:
df_boston = pd.read_csv('./data/boston.csv')
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

## 열과 행 선택하기

In [18]:
result = df_boston[['CRIM', 'ZN', 'INDUS']]
result.head()

CRIM    ZN  INDUS
0  0.00632  18.0   2.31
1  0.02731   0.0   7.07
2  0.02729   0.0   7.07
3  0.03237   0.0   2.18
4  0.06905   0.0   2.18

In [20]:
#열을 선택할 때, 컬럼명을 따로 정리해주는게 편함
cols = ['CRIM', 'ZN', 'INDUS']
result = df_boston[cols]
result.head(1)

CRIM    ZN  INDUS
0  0.00632  18.0   2.31

In [25]:
# ZN이 18.0에 해당하는 행만 추출
# 행추출의 기본 원리는 조건문
result = df_boston[df_boston['ZN'] == 18.0]
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE   DIS  RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.09  1.0  296.0     15.3   

       B  LSTAT  target  
0  396.9   4.98    24.0

In [32]:
# AGE가 50 이상
# reset_index(drop=True) 같이 해줘야, 깔끔하게 볼 수 있음
result = df_boston[df_boston['AGE'] >= 50].reset_index(drop=True)
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
4    0.02985   0.0   2.18   0.0  0.458  6.430  58.7  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
354  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
355  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
356  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
357  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
358  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  396.90   5.33    36.2  
4       18.7  394.12   5.21    28.7  
..       ...     ...    ...     ...  
354     21.0  391.99   9.67    22.4  
355     21.0  396.90   9.08    20.6  
356     21.0  396.90   5.64    23.9  
357     21.0  393.45   6.48    22.0  
358     21.0  396.90   7.88    11.9  

[359 rows x 14 columns]

In [44]:
# INDUS가 5.0이상이면서, B가 394이상인 데이터 (동시만족 and)
# 소괄호로 조건을 묶어주고, & 기호로 연결
# result = df[(조건식1) & (조건식2)] 처럼 틀을 잡아주고 시작

result = df_boston[(df_boston['INDUS'] >= 5.0) & (df_boston['B'] >= 394)].reset_index(drop=True)
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
1    0.08829  12.5   7.87   0.0  0.524  6.012  66.6  5.5605  5.0  311.0   
2    0.14455  12.5   7.87   0.0  0.524  6.172  96.1  5.9505  5.0  311.0   
3    0.11747  12.5   7.87   0.0  0.524  6.009  82.9  6.2267  5.0  311.0   
4    0.62976   0.0   8.14   0.0  0.538  5.949  61.8  4.7075  4.0  307.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
138  0.17783   0.0   9.69   0.0  0.585  5.569  73.5  2.3999  6.0  391.0   
139  0.22438   0.0   9.69   0.0  0.585  6.027  79.7  2.4982  6.0  391.0   
140  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
141  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
142  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       17.8  396.90   9.14    21.6  
1       15.2  395.60  12.43    22.9  
2       15.2  396.90  19.15    27.1  
3       15.2  396.90  13.27    18.9  
4       21.0  396.90   8.26    20.4  
..       ...     ...    ...     ...  
138     19.2  395.77  15.10    17.5  
139     19.2  396.90  14.33    16.8  
140     21.0  396.90   9.08    20.6  
141     21.0  396.90   5.64    23.9  
142     21.0  396.90   7.88    11.9  

[143 rows x 14 columns]

In [45]:
# 또는(or)로 할 경우 : | 기호로 연결
result = df_boston[(df_boston['INDUS'] >= 5.0) | (df_boston['B'] >= 394)].reset_index(drop=True)
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
429  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
430  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
431  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
432  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
433  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
429     21.0  391.99   9.67    22.4  
430     21.0  396.90   9.08    20.6  
431     21.0  396.90   5.64    23.9  
432     21.0  393.45   6.48    22.0  
433     21.0  396.90   7.88    11.9  

[434 rows x 14 columns]

## iloc 와 loc
- iloc (Integer Location-based Indexing): 정수 인덱스를 기반으로 행과 열을 선택
- loc (Label-based Indexing): 레이블을 기반으로 행과 열을 선택 -> 행과 열의 이름(레이블)을 사용하여 데이터에 접근

In [48]:
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [56]:
#iloc 활용
result = df_boston.iloc[0:3,0:3]
result

CRIM    ZN  INDUS
0  0.00632  18.0   2.31
1  0.02731   0.0   7.07
2  0.02729   0.0   7.07

In [61]:
#loc 활용 >> iloc보다 시간이 좀 더 걸리지만, 데이터 가공하긴 이게 편함
result = df_boston.loc[[0, 1, 2],['CRIM', 'ZN', 'INDUS']]
result = df_boston.loc[0:2, ['CRIM', 'ZN', 'INDUS']]

# 이렇게 조건을 걸어서 행열 추출시 loc가 더 유용
result2 = df_boston.loc[df_boston['INDUS'] >= 5.0,['CRIM', 'ZN', 'INDUS']]
result2

CRIM    ZN  INDUS
1    0.02731   0.0   7.07
2    0.02729   0.0   7.07
6    0.08829  12.5   7.87
7    0.14455  12.5   7.87
8    0.21124  12.5   7.87
..       ...   ...    ...
501  0.06263   0.0  11.93
502  0.04527   0.0  11.93
503  0.06076   0.0  11.93
504  0.10959   0.0  11.93
505  0.04741   0.0  11.93

[386 rows x 3 columns]

In [60]:
# 행열 추출시, 행 추출 조건 2개 이상도 가능
result3 = df_boston.loc[(df_boston['INDUS'] >= 5.0) & (df_boston['B'] >= 394)
                        , ['CRIM', 'ZN', 'INDUS']].reset_index(drop=True)
result3

CRIM    ZN  INDUS
0    0.02731   0.0   7.07
1    0.08829  12.5   7.87
2    0.14455  12.5   7.87
3    0.11747  12.5   7.87
4    0.62976   0.0   8.14
..       ...   ...    ...
138  0.17783   0.0   9.69
139  0.22438   0.0   9.69
140  0.04527   0.0  11.93
141  0.06076   0.0  11.93
142  0.04741   0.0  11.93

[143 rows x 3 columns]

## 결측치 다루기

In [74]:
import pandas as pd
import numpy as np

np.random.seed(0)
data = np.random.randint(0, 10, size = (10, 3)).astype(float)
print(data)

[[5. 0. 3.]
 [3. 7. 9.]
 [3. 5. 2.]
 [4. 7. 6.]
 [8. 8. 1.]
 [6. 7. 7.]
 [8. 1. 5.]
 [9. 8. 9.]
 [4. 3. 0.]
 [3. 5. 0.]]


In [75]:
data[data < 3] = np.nan
print(data)

[[ 5. nan  3.]
 [ 3.  7.  9.]
 [ 3.  5. nan]
 [ 4.  7.  6.]
 [ 8.  8. nan]
 [ 6.  7.  7.]
 [ 8. nan  5.]
 [ 9.  8.  9.]
 [ 4.  3. nan]
 [ 3.  5. nan]]


In [76]:
df = pd.DataFrame(data, columns=["col1", "col2", "col3"]) #외부에서 가져온 새로운 데이터라고 가정
df.info() #결측치가 얼마나 되는지 대충 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    10 non-null     float64
 1   col2    8 non-null      float64
 2   col3    6 non-null      float64
dtypes: float64(3)
memory usage: 368.0 bytes


In [77]:
#전체적인 결측치 규모 확인
df.isna().sum()

col1    0
col2    2
col3    4
dtype: int64

In [80]:
#결측치를 평균으로 대치
col2_mean = df['col2'].mean()
col3_mean = df['col3'].mean()

df['col3'] = df['col3'].fillna(col3_mean)
df['col2'] = df['col2'].fillna(df['col2'].mean())
df

col1  col2  col3
0   5.0  6.25   3.0
1   3.0  7.00   9.0
2   3.0  5.00   6.5
3   4.0  7.00   6.0
4   8.0  8.00   6.5
5   6.0  7.00   7.0
6   8.0  6.25   5.0
7   9.0  8.00   9.0
8   4.0  3.00   6.5
9   3.0  5.00   6.5

In [81]:
df = pd.DataFrame({
    "이름": ["Evan", "Sara", "Chris", "Messi", "Woods", "Jordan"], 
    "국어": [70, 90, None, None, 100, 85], 
    "영어": [65, 100, None, 90, 70, 80]
})

df

이름     국어     영어
0    Evan   70.0   65.0
1    Sara   90.0  100.0
2   Chris    NaN    NaN
3   Messi    NaN   90.0
4   Woods  100.0   70.0
5  Jordan   85.0   80.0

## 행 추가

In [82]:
df.loc[6, "이름":"영어"] = ['KIM', 50, 60]
df

이름     국어     영어
0    Evan   70.0   65.0
1    Sara   90.0  100.0
2   Chris    NaN    NaN
3   Messi    NaN   90.0
4   Woods  100.0   70.0
5  Jordan   85.0   80.0
6     KIM   50.0   60.0

In [86]:
# 국어점수가 90점 이상이면 "A"
# 국어점수가 80점~89점 "B"
# 국어점수가 70점~79점 "C"
# 나머지는 F

def grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    else:
        return 'F'

df['국어 등급'] = df['국어'].apply(grade)

print(df)


       이름     국어     영어 국어 등급 점수
0    Evan   70.0   65.0     C  C
1    Sara   90.0  100.0     A  A
2   Chris    NaN    NaN     F  F
3   Messi    NaN   90.0     F  F
4   Woods  100.0   70.0     A  A
5  Jordan   85.0   80.0     B  B
6     KIM   50.0   60.0     F  F


### np 조건문
- np.select : 다중조건식, 다중결과값, default => else 조건
- np.where(조건식, 참, np.where(조건식, 참)...)

In [87]:
# numpy와 pandas 연계 예시

condition_list = [(df["국어"] >= 90), (df['국어'] >= 80) & (df['국어'] < 90), (df['국어'] >= 70) & (df['국어'] < 80)]
choice_list = ["A", "B", "C"]
df['점수'] = np.select(condition_list, choice_list, default = "F")
df

이름     국어     영어 국어 등급 점수
0    Evan   70.0   65.0     C  C
1    Sara   90.0  100.0     A  A
2   Chris    NaN    NaN     F  F
3   Messi    NaN   90.0     F  F
4   Woods  100.0   70.0     A  A
5  Jordan   85.0   80.0     B  B
6     KIM   50.0   60.0     F  F

## 날짜 데이터
- to_datetime 을 문자열과 리스트에 각각 적용해보기

In [4]:
#문자열에 to_datetime => timestamp
date_string = "2023-03-02"
print(type(date_string))

datetime_obj = pd.to_datetime(date_string)
print(datetime_obj)
print(type(datetime_obj))

<class 'str'>
2023-03-02 00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>


In [5]:
#리스트에 to_datetime => datetime64
date_list = ["2023-03-02"]
print(type(date_list))

datetime_obj = pd.to_datetime(date_list)
print(datetime_obj)
print(type(datetime_obj))

<class 'list'>
DatetimeIndex(['2023-03-02'], dtype='datetime64[ns]', freq=None)
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>


## 데이터 가져오기
- 실습 데이터 : raw_sales.csv

In [6]:
sales = pd.read_csv("./data/raw_sales.csv")
sales.head()

datesold  postcode   price propertyType  bedrooms
0  2007-02-07 00:00:00      2607  525000        house         4
1  2007-02-27 00:00:00      2906  290000        house         3
2  2007-03-07 00:00:00      2905  328000        house         3
3  2007-03-09 00:00:00      2905  380000        house         4
4  2007-03-21 00:00:00      2906  310000        house         3

In [7]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   datesold      29580 non-null  object
 1   postcode      29580 non-null  int64 
 2   price         29580 non-null  int64 
 3   propertyType  29580 non-null  object
 4   bedrooms      29580 non-null  int64 
dtypes: int64(3), object(2)
memory usage: 1.1+ MB


In [8]:
#날짜 데이터가 object -> 날짜데이터로 변환
sales['datesold'] = pd.to_datetime(sales['datesold'])

In [9]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 1.1+ MB


In [10]:
sales.head(1)

datesold  postcode   price propertyType  bedrooms
0 2007-02-07      2607  525000        house         4

In [11]:
# 연도, 월, 일 로 변환
sales['year'] = sales['datesold'].dt.year
sales['month'] = sales['datesold'].dt.month
sales['day'] = sales['datesold'].dt.day
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
 5   year          29580 non-null  int32         
 6   month         29580 non-null  int32         
 7   day           29580 non-null  int32         
dtypes: datetime64[ns](1), int32(3), int64(3), object(1)
memory usage: 1.5+ MB


## shift 기능
- 시계열 데이터 다룰 때 유용
- 예) 전일 대비 증가액/증가율 등

In [12]:
temp_df = sales.loc[:, ['datesold', 'price']].copy()
temp_df.head(3)

datesold   price
0 2007-02-07  525000
1 2007-02-27  290000
2 2007-03-07  328000

In [13]:
temp_df['shifted_v1'] = temp_df['price'].shift(1, fill_value=0).astype(int)
temp_df['diff'] = temp_df['price'] - temp_df['shifted_v1']
temp_df.head()

datesold   price  shifted_v1    diff
0 2007-02-07  525000           0  525000
1 2007-02-27  290000      525000 -235000
2 2007-03-07  328000      290000   38000
3 2007-03-09  380000      328000   52000
4 2007-03-21  310000      380000  -70000

In [118]:
temp_df['shifted_v2'] = temp_df['price'].shift(2, fill_value=0).astype(int)
temp_df['diff_2'] = temp_df['price'] - temp_df['shifted_v2']
temp_df.head(1)

datesold   price  shifted_v1    diff  shifted_v2  diff_2
0 2007-02-07  525000           0  525000           0  525000

In [124]:
temp_df = sales.loc[:, ['datesold', 'price']].copy()
temp_df['shifted_v3'] = temp_df['price'].shift(-1, fill_value=0).astype(int)
temp_df['shifted_v4'] = temp_df['price'].shift(-2, fill_value=0).astype(int)

temp_df.tail()

datesold   price  shifted_v3  shifted_v4
29575 2019-07-25  500000      560000      464950
29576 2019-07-25  560000      464950      589000
29577 2019-07-26  464950      589000      775000
29578 2019-07-26  589000      775000           0
29579 2019-07-26  775000           0           0

### mission_

In [128]:
sales.info()
sales.head(1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
 5   year          29580 non-null  int32         
 6   month         29580 non-null  int32         
 7   day           29580 non-null  int32         
dtypes: datetime64[ns](1), int32(3), int64(3), object(1)
memory usage: 1.5+ MB


datesold  postcode   price propertyType  bedrooms  year  month  day
0 2007-02-07      2607  525000        house         4  2007      2    7

In [133]:
sales['한글날짜'] = sales['datesold'].dt.strftime('%Y년 %m월 %d일')
sales.head()

datesold  postcode   price propertyType  bedrooms  year  month  day  \
0 2007-02-07      2607  525000        house         4  2007      2    7   
1 2007-02-27      2906  290000        house         3  2007      2   27   
2 2007-03-07      2905  328000        house         3  2007      3    7   
3 2007-03-09      2905  380000        house         4  2007      3    9   
4 2007-03-21      2906  310000        house         3  2007      3   21   

            한글날짜  
0  2007년 02월 07일  
1  2007년 02월 27일  
2  2007년 03월 07일  
3  2007년 03월 09일  
4  2007년 03월 21일

## 결측치 처리해보기

In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import statsmodels
import scipy
import seaborn as sns

print(pd.__version__)
print(np.__version__)
print(matplotlib.__version__)
print(statsmodels.__version__)
print(scipy.__version__)
print(sns.__version__)

2.0.3
1.25.2
3.7.2
0.14.0
1.11.1
0.12.2


In [10]:
DATA_PATH = './'
covidtotals = pd.read_csv(DATA_PATH + "data/covidtotalswithmissings.csv")

### pd.set_option()

In [11]:
pd.set_option('display.width', 80)
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_rows', 20)

pd.options.display.float_format = '{:,.2f}'.format

In [12]:
covidtotals = covidtotals.set_index('iso_code')

In [13]:
covidtotals.head()

lastdate     location  total_cases  total_deaths  total_cases_pm  \
iso_code                                                                       
AFG       2020-06-01  Afghanistan        15205           257          390.59   
ALB       2020-06-01      Albania         1137            33          395.09   
DZA       2020-06-01      Algeria         9394           653          214.22   
AND       2020-06-01      Andorra          764            51        9,888.05   
AGO       2020-06-01       Angola           86             4            2.62   

          total_deaths_pm    population  pop_density  median_age  \
iso_code                                                           
AFG                  6.60 38,928,341.00        54.42       18.60   
ALB                 11.47  2,877,800.00       104.87       38.00   
DZA                 14.89 43,851,043.00        17.35       29.10   
AND                660.07     77,265.00       163.75         NaN   
AGO                  0.12 32,866,268.00        23.89       16.80   

          gdp_per_capita  hosp_beds  
iso_code                             
AFG             1,803.99       0.50  
ALB            11,803.43       2.89  
DZA            13,913.84       1.90  
AND                  NaN        NaN  
AGO             5,819.49        NaN

## 결측치 처리 
- 컬럼방향으로 결측지 갯수 파악하기
- 5가지 인구통계 변수 중 3개가 누락된 곳 찾아보기

In [14]:
totvars = ['location','total_cases','total_deaths','total_cases_pm','total_deaths_pm']
demovars = ['population','pop_density','median_age','gdp_per_capita', 'hosp_beds']

In [20]:
# 열 별로 결측치 수 파악
covidtotals[demovars].isnull().sum(axis=0)

population         0
pop_density       12
median_age        24
gdp_per_capita    28
hosp_beds         46
dtype: int64

In [16]:
covidtotals.iloc[2:4, :]

lastdate location  total_cases  total_deaths  total_cases_pm  \
iso_code                                                                   
DZA       2020-06-01  Algeria         9394           653          214.22   
AND       2020-06-01  Andorra          764            51        9,888.05   

          total_deaths_pm    population  pop_density  median_age  \
iso_code                                                           
DZA                 14.89 43,851,043.00        17.35       29.10   
AND                660.07     77,265.00       163.75         NaN   

          gdp_per_capita  hosp_beds  
iso_code                             
DZA            13,913.84       1.90  
AND                  NaN        NaN

In [43]:
# 행에서의 결측치 수 파악
demovars_misscnt = covidtotals[demovars].isnull().sum(axis=1)
demovars_misscnt.value_counts()
print(demovars_misscnt) #시리즈임
print(type(demovars_misscnt))

iso_code
AFG    0
ALB    0
DZA    0
AND    3
AGO    1
      ..
VNM    0
ESH    3
YEM    0
ZMB    0
ZWE    0
Length: 210, dtype: int64
<class 'pandas.core.series.Series'>


### 미션1
- 결측치가 3개 이상인 (행) 데이터 추출하기
- 추출해야할 컬럼은 ['location']과 demovars

In [50]:
#행과 열을 기준으 잘생각해보자! (index alignment 적용)
demovars_misscnt = covidtotals[demovars].isnull().sum(axis=1)
covidtotals.loc[demovars_misscnt >= 3, ['location']+demovars].T
#covidtotals.loc[demovars_misscnt >= 3, ['location']+demovars]

iso_code             AND       AIA                              BES  \
location         Andorra  Anguilla  Bonaire Sint Eustatius and Saba   
population     77,265.00 15,002.00                        26,221.00   
pop_density       163.75       NaN                              NaN   
median_age           NaN       NaN                              NaN   
gdp_per_capita       NaN       NaN                              NaN   
hosp_beds            NaN       NaN                              NaN   

iso_code                           VGB             FRO               FLK  \
location        British Virgin Islands  Faeroe Islands  Falkland Islands   
population                   30,237.00       48,865.00          3,483.00   
pop_density                     207.97           35.31               NaN   
median_age                         NaN             NaN               NaN   
gdp_per_capita                     NaN             NaN               NaN   
hosp_beds                          NaN             NaN               NaN   

iso_code              GIB        GRL       GGY          IMN        JEY  \
location        Gibraltar  Greenland  Guernsey  Isle of Man     Jersey   
population      33,691.00  56,772.00 67,052.00    85,032.00 101,073.00   
pop_density      3,457.10       0.14       NaN       147.87        NaN   
median_age            NaN        NaN       NaN          NaN        NaN   
gdp_per_capita        NaN        NaN       NaN          NaN        NaN   
hosp_beds             NaN        NaN       NaN          NaN        NaN   

iso_code                XKX         MSR                       MNP  \
location             Kosovo  Montserrat  Northern Mariana Islands   
population     1,932,774.00    4,999.00                 57,557.00   
pop_density             NaN         NaN                    119.88   
median_age              NaN         NaN                       NaN   
gdp_per_capita          NaN         NaN                       NaN   
hosp_beds               NaN         NaN                       NaN   

iso_code                 TWN                       TCA      VAT  \
location              Taiwan  Turks and Caicos Islands  Vatican   
population     23,816,775.00                 38,718.00   809.00   
pop_density              NaN                     37.31      NaN   
median_age             42.20                       NaN      NaN   
gdp_per_capita           NaN                       NaN      NaN   
hosp_beds                NaN                       NaN      NaN   

iso_code                   ESH  
location        Western Sahara  
population          597,330.00  
pop_density                NaN  
median_age               28.40  
gdp_per_capita             NaN  
hosp_beds                  NaN

## Index Alignment
- 인덱스의 값끼리 연산이 이뤄지는 것을 말함. Pandas 에서 제공.

In [51]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])\

# print(s1, "\n", s2)
print(s1 + s2)

a    2
b    4
c    6
d    8
dtype: int64


## 코로나 관련 변수만 결측치 확인
- 결측값이 있는지 확인
- 결측값이 있는 국가 하나 찾기

In [60]:
totvars = ['location','total_cases','total_deaths','total_cases_pm','total_deaths_pm']
covidtotals.head(1)

lastdate     location  total_cases  total_deaths  total_cases_pm  \
iso_code                                                                       
AFG       2020-06-01  Afghanistan        15205           257          390.59   

          total_deaths_pm    population  pop_density  median_age  \
iso_code                                                           
AFG                  6.60 38,928,341.00        54.42       18.60   

          gdp_per_capita  hosp_beds  
iso_code                             
AFG             1,803.99       0.50

In [62]:
blank = covidtotals[totvars].isnull().sum(axis=1)
blank

iso_code
AFG    0
ALB    0
DZA    0
AND    0
AGO    0
      ..
VNM    0
ESH    0
YEM    0
ZMB    0
ZWE    0
Length: 210, dtype: int64

In [67]:
covidtotals.loc[blank != 0, :]

lastdate   location  total_cases  total_deaths  total_cases_pm  \
iso_code                                                                     
HKG       2020-05-26  Hong Kong            0             0             NaN   

          total_deaths_pm   population  pop_density  median_age  \
iso_code                                                          
HKG                   NaN 7,496,988.00     7,039.71       44.80   

          gdp_per_capita  hosp_beds  
iso_code                             
HKG            56,054.92        NaN

In [71]:
# 강사님 답
covidtotals[totvars].isnull().sum(axis=0)
totvarsmisscnt = covidtotals[totvars].isnull().sum(axis=1)
covidtotals.loc[totvarsmisscnt>0].T

iso_code                 HKG
lastdate          2020-05-26
location           Hong Kong
total_cases                0
total_deaths               0
total_cases_pm           NaN
total_deaths_pm          NaN
population      7,496,988.00
pop_density         7,039.71
median_age             44.80
gdp_per_capita     56,054.92
hosp_beds                NaN

In [74]:
covidtotalsonly = covidtotals.loc[:, totvars]
covidtotalsonly['total_cases_q'] = pd.qcut(covidtotalsonly['total_cases'],
                                         labels = ['매우낮음', '낮음', '보통', '높음', '매우높음'],
                                         q=5, precision=0)
covidtotalsonly['total_deaths_q'] = pd.qcut(covidtotalsonly['total_deaths'],
                                         labels = ['매우낮음', '낮음', '보통', '높음', '매우높음'],
                                         q=5, precision=0)

covidtotalsonly.head()

location  total_cases  total_deaths  total_cases_pm  \
iso_code                                                           
AFG       Afghanistan        15205           257          390.59   
ALB           Albania         1137            33          395.09   
DZA           Algeria         9394           653          214.22   
AND           Andorra          764            51        9,888.05   
AGO            Angola           86             4            2.62   

          total_deaths_pm total_cases_q total_deaths_q  
iso_code                                                
AFG                  6.60            높음             높음  
ALB                 11.47            보통             보통  
DZA                 14.89            높음           매우높음  
AND                660.07            보통             보통  
AGO                  0.12          매우낮음             낮음

In [75]:
pd.crosstab(covidtotalsonly['total_cases_q'], covidtotalsonly['total_deaths_q'])

total_deaths_q  매우낮음  낮음  보통  높음  매우높음
total_cases_q                         
매우낮음              34   7   1   0     0
낮음                12  19  10   1     0
보통                 1  13  15  13     0
높음                 0   0  12  24     6
매우높음               0   0   2   4    36

In [80]:
covidtotalsonly.loc[(covidtotalsonly['total_cases_q'] =='낮음') & (covidtotalsonly['total_deaths_q'] == '높음')].T

iso_code           YEM
location         Yemen
total_cases        323
total_deaths        80
total_cases_pm   10.83
total_deaths_pm   2.68
total_cases_q       낮음
total_deaths_q      높음